# Generated by Django 2.0 on 2018-01-20 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('path', models.CharField(max_length=200, verbose_name='文件路径')),
                ('type', models.CharField(choices=[('0', '目录'), ('1', '文件')], default='0', max_length=3)),
                ('state', models.CharField(choices=[('1', '正常'), ('2', '删除'), ('3', '即将上线')], default='1', max_length=3)),
                ('views', models.IntegerField(default=0, verbose_name='点击数量')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('has_summary', models.BooleanField(default=False, verbose_name='是否有有摘要')),
                ('has_note', models.BooleanField(default=False, verbose_name='是否有首行注释')),
                ('has_question', models.BooleanField(default=False, verbose_name='是否添加0行问题')),
                ('has_sonar', models.BooleanField(default=False, verbose_name='是否通过sonar获取问题')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'Source_File',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(default='', max_length=300, verbose_name='摘要')),
                ('note', models.TextField(default='', verbose_name='首行注释')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.File', verbose_name='文件')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
                'db_table': 'Source_FileInfo',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='编程语言')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '编程语言',
                'verbose_name_plural': '编程语言',
                'db_table': 'Source_Language',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='工程名称')),
                ('desc', models.TextField(verbose_name='描述')),
                ('path', models.CharField(max_length=200, verbose_name='工程路径')),
                ('github', models.URLField(max_length=100, verbose_name='Github网址')),
                ('ossean', models.URLField(max_length=100, verbose_name='Ossean网址')),
                ('files', models.IntegerField(default=0, verbose_name='文件数量')),
                ('views', models.IntegerField(default=0, verbose_name='点击数量')),
                ('state', models.CharField(choices=[('1', '正常'), ('2', '删除'), ('3', '即将上线')], default='1', max_length=3)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Language', verbose_name='编程语言')),
                ('uploader', models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '工程',
                'verbose_name_plural': '工程',
                'db_table': 'Source_Project',
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='工程')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '源码关注',
                'verbose_name_plural': '源码关注',
                'db_table': 'Source_Watch',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='工程名称'),
        ),
        migrations.AddField(
            model_name='file',
            name='super_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.File', verbose_name='上级目录'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['views'], name='Source_Proj_views_b88a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['create_time'], name='Source_Proj_create__8fc38f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['uploader'], name='Source_Proj_uploade_f0fd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['views'], name='Source_File_views_b70b17_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['create_time'], name='Source_File_create__754bb1_idx'),
        ),
    ]
