# Generated by Django 2.0.1 on 2018-01-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('path', models.CharField(max_length=200, verbose_name='文件路径')),
                ('type', models.CharField(choices=[('0', '目录'), ('1', '文件')], default='0', max_length=3)),
                ('state', models.CharField(choices=[('1', '正常'), ('2', '删除'), ('3', '即将上线')], default='1', max_length=3)),
                ('views', models.IntegerField(default=0, verbose_name='点击数量')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('has_summary', models.BooleanField(default=False, verbose_name='是否有有摘要')),
                ('has_note', models.BooleanField(default=False, verbose_name='是否有首行注释')),
                ('has_question', models.BooleanField(default=False, verbose_name='是否添加0行问题')),
                ('has_sonar', models.BooleanField(default=False, verbose_name='是否通过sonar获取问题')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'Source_File',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(default='', max_length=300, verbose_name='摘要')),
                ('note', models.TextField(default='', verbose_name='首行注释')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
                'db_table': 'Source_FileInfo',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='编程语言')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '编程语言',
                'verbose_name_plural': '编程语言',
                'db_table': 'Source_Language',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='工程名称')),
                ('desc', models.TextField(verbose_name='描述')),
                ('path', models.CharField(max_length=200, verbose_name='工程路径')),
                ('github', models.URLField(max_length=100, verbose_name='Github网址')),
                ('ossean', models.URLField(max_length=100, verbose_name='Ossean网址')),
                ('files', models.IntegerField(default=0, verbose_name='文件数量')),
                ('views', models.IntegerField(default=0, verbose_name='点击数量')),
                ('state', models.CharField(choices=[('1', '正常'), ('2', '删除'), ('3', '即将上线')], default='1', max_length=3)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工程',
                'verbose_name_plural': '工程',
                'db_table': 'Source_Project',
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='工程')),
            ],
            options={
                'verbose_name': '源码关注',
                'verbose_name_plural': '源码关注',
                'db_table': 'Source_Watch',
            },
        ),
    ]
