# Generated by Django 2.0.1 on 2018-01-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Language', verbose_name='编程语言'),
        ),
        migrations.AddField(
            model_name='project',
            name='uploader',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.File', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='工程名称'),
        ),
        migrations.AddField(
            model_name='file',
            name='super_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.File', verbose_name='上级目录'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['views'], name='Source_Proj_views_b88a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['create_time'], name='Source_Proj_create__8fc38f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['uploader'], name='Source_Proj_uploade_f0fd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['views'], name='Source_File_views_b70b17_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['create_time'], name='Source_File_create__754bb1_idx'),
        ),
    ]
