# Generated by Django 2.0.1 on 2018-04-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180126_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='src',
            field=models.CharField(default=None, max_length=50, verbose_name='编程语言源代码'),
            preserve_default=False,
        ),
    ]
