# Generated by Django 2.0.1 on 2018-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_language_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='src',
            field=models.CharField(max_length=50, null=True, verbose_name='编程语言源代码'),
        ),
    ]
