# Generated by Django 2.0.1 on 2018-04-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180401_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='anno_nums',
            field=models.IntegerField(default=0, verbose_name='注释数量'),
        ),
        migrations.AddField(
            model_name='file',
            name='question_nums',
            field=models.IntegerField(default=0, verbose_name='注释数量'),
        ),
    ]
