# Generated by Django 2.0.1 on 2018-04-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180407_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='anno_nums',
            new_name='anno_num',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='question_nums',
            new_name='question_num',
        ),
    ]
