# Generated by Django 2.0.1 on 2018-04-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180407_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='question_num',
            new_name='issue_num',
        ),
    ]
