# Generated by Django 2.0.1 on 2018-04-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180408_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnnoIssueSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_num', models.IntegerField(default=0, verbose_name='注释总数')),
                ('isuue_num', models.IntegerField(default=0, verbose_name='问题总数')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.File', verbose_name='文件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='文件')),
            ],
            options={
                'verbose_name': '文件注释问题总数',
                'verbose_name_plural': '文件注释问题总数',
                'db_table': 'File_Anno_Issue_Summary',
            },
        ),
    ]
