# Generated by Django 2.0.1 on 2018-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_fileannoissuesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileannoissuesummary',
            name='parent_path',
            field=models.CharField(default='', max_length=255, verbose_name='父文件夹路径'),
        ),
    ]
