# Generated by Django 2.0.1 on 2018-01-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Question', verbose_name='问题'),
        ),
    ]
