# Generated by Django 2.0 on 2018-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ManyToManyField(blank=True, null=True, to='users.Grade', verbose_name='班级'),
        ),
    ]
