# Generated by Django 2.0.1 on 2018-01-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('linenum', models.IntegerField(default=0, verbose_name='注释行号')),
                ('state', models.CharField(choices=[('2', '正常'), ('4', '关闭'), ('6', '删除'), ('8', '锁定')], default='2', max_length=3)),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '注释',
                'verbose_name_plural': '注释',
                'db_table': 'Annotation',
            },
        ),
        migrations.CreateModel(
            name='AnnotationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '注释评论',
                'verbose_name_plural': '注释评论',
                'db_table': 'Annotation_Comment',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'db_table': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '回答评论',
                'verbose_name_plural': '回答评论',
                'db_table': 'Answer_Comment',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('summary', models.TextField(verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('state', models.CharField(choices=[('2', '正常'), ('4', '关闭'), ('6', '删除'), ('8', '锁定')], default='2', max_length=3)),
                ('weight', models.FloatField(default='0', max_length=3)),
                ('views', models.IntegerField(default=0, verbose_name='点击数量')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
                'db_table': 'Article_Comment',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='issue内容')),
                ('issue_type', models.CharField(choices=[('1', '选择题'), ('2', '问答题')], default='1', max_length=3, verbose_name='Issue类型')),
                ('issue_info', models.CharField(choices=[('1', '错误程度'), ('2', '错误类型'), ('3', '存在错误')], max_length=3, null=True, verbose_name='Issue信息')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('sonar_id', models.IntegerField(null=True, verbose_name='Sonar')),
                ('linenum', models.IntegerField(null=True, verbose_name='Issue行号')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issue',
                'db_table': 'Issue',
            },
        ),
        migrations.CreateModel(
            name='IssueAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('correct', models.BooleanField(default=True, verbose_name='正确与否')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'db_table': 'Issue_Answer',
            },
        ),
        migrations.CreateModel(
            name='IssueChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(default='', verbose_name='选项内容')),
                ('choice_position', models.CharField(default='', max_length=10, verbose_name='选项位置')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '选择题选项',
                'verbose_name_plural': '选择题选项',
                'db_table': 'Issue_Choice',
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Issue评论',
                'verbose_name_plural': 'Issue评论',
                'db_table': 'Issue_Comment',
            },
        ),
        migrations.CreateModel(
            name='IssueStandardAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_position', models.CharField(default='', max_length=500, verbose_name='正确选项位置')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Issue参考答案',
                'verbose_name_plural': 'Issue参考答案',
                'db_table': 'Issue_Standard_Answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='问题内容')),
                ('vote', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('linenum', models.IntegerField(null=True, verbose_name='问题行号')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Question', verbose_name='Issue')),
            ],
            options={
                'verbose_name': '问题评论',
                'verbose_name_plural': '问题评论',
                'db_table': 'Question_Comment',
            },
        ),
    ]
