# Generated by Django 2.0 on 2018-01-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlecomment',
            table='Article_Comment',
        ),
    ]
