# Generated by Django 2.0.1 on 2018-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180126_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='update_nums',
            field=models.IntegerField(default=0, verbose_name='修改次数'),
        ),
    ]
