# Generated by Django 2.0.1 on 2018-01-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_annotation_update_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
