# Generated by Django 2.0.1 on 2018-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueanswer',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
