# Generated by Django 2.0.1 on 2018-01-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0005_issueanswer_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, '点赞'), (-1, '点踩')], default=0, verbose_name='点赞类型')),
                ('vote_type', models.CharField(choices=[('question', '问题'), ('answer', '回答'), ('article', '文章'), ('annotation', '注释'), ('issue', 'issue'), ('issue_answer', 'issue回答'), ('question_comment', '问题评论'), ('answer_comment', '回答评论'), ('article_comment', '文章评论'), ('annotation_comment', '注释评论'), ('file', '代码文件')], default='', max_length=20, verbose_name='点赞对象名称')),
                ('vote_type_id', models.IntegerField(default=0, verbose_name='点赞对象id')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'db_table': 'Vote',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='是否被采纳'),
        ),
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.CharField(choices=[('2', '正常'), ('4', '关闭'), ('6', '已解决'), ('8', '锁定')], default='2', max_length=3),
        ),
    ]
