# Generated by Django 2.0.1 on 2018-04-18 20:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0006_auto_20180126_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='QuestionAnswer',
        ),
        migrations.RenameModel(
            old_name='AnswerComment',
            new_name='QuestionAnswerComment',
        ),
    ]
