# Generated by Django 2.0.1 on 2018-04-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20180418_2056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionanswer',
            table='Question_Answer',
        ),
        migrations.AlterModelTable(
            name='questionanswercomment',
            table='Question_Answer_Comment',
        ),
    ]
