# Generated by Django 2.0.1 on 2018-05-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_fileannoissuesummary_parent_path'),
        ('operations', '0008_auto_20180418_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(0, 'get_all_annotation'), (1, 'get_user_annotation')], default=0, verbose_name='策略')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '注释策略',
                'verbose_name_plural': '注释策略',
                'db_table': 'AnnotationStrategy',
            },
        ),
    ]
